# DirtMultiVersion configuration file

# Server version
#
# Allowed values:
# B1_2, B1_3, B1_4, B1_5, B1_6_6, B1_7_3, B1_8_1,
# R1_0, R1_1, R1_2_1, R1_2_4, R1_3_1,
# R1_4_6, R1_5_1, R1_5_2, R1_6_1, R1_6_2, R1_6_4, R1_7_2, R1_7_6
server_version: "B1_7_3"
# Address to listen for connections
bind_address: "localhost"
# Port to listen for connections
bind_port: 25565
# Remote server address
remote_address: "localhost"
# Remote server port
remote_port: 25567
# Max packets per second
#
# change that value when normal players
# are getting disconnected by doing completely normal things
max_packets_per_second: 150
# The delay before a client is allowed to connect again
# after a recent connection attempt, including pinging
connection_throttle: 350
# Compression threshold
# -1 to disable, 0 to compress all packets
compression_threshold: 256
# Caches blocks only above Y 20 (for b1.7 servers)
reduce_blockstorage_memory: false
# Max connections to proxy (not server)
max_proxy_connections: 20
# MOTD for versions where Server Ping Protocol was not available
prerelease_motd: "A Minecraft Server"
# Visible max online in MOTD
prerelease_motd_max_online: 20
# Replace chests to ender chests to prevent rendering glitches (r1.3+)
replace_chests: true
# Enable ViaVersion support (experimental)
viaversion_support: true
# Enable command logging to console
enable_command_logging: false